version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Only run the build job for the main branch
      - security_scan: 
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - main  # Only deploy on the main branch
          requires:
            - build  
            - security_scan  

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: cimg/node:10.16.3 
    steps:
      - checkout  # Check out the source code from the repository
      - run:
          name: update-npm
          command: npm install -g npm@5
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}  # Restore cached dependencies based on package-lock.json
      - run:
          name: install-npm
          command: npm install  # Install project dependencies
      - run:
          name: audit-packages
          command: npm audit    # Checking vulnerabilities
      - run:
          name: test-run
          command: npm run test  # Run the tests
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}  # Cache the dependencies for future builds
          paths:
            - ./node_modules

  security_scan:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Snyk
          command: sudo npm install -g snyk  # Install the Snyk security tool globally
      - run:
          name: Authenticate with Snyk
          command: snyk auth $SNYK_TOKEN  # Using environment variable
      - run:
          name: Run Snyk Security Scan
          command: snyk test || true  # Run Snyk test
      - run:
          name: Monitor Security Issues
          command: snyk monitor  # Monitor the project for security issues

  deploy:
    docker:
      - image: cimg/node:10.16.3 
    steps:
      - run:
          name: deploy-app
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf CA1-DevOps-20225431/; git clone https://github.com/RutwikAmbre/CA1-DevOps-20225431.git; source CA1-DevOps-20225431/deployApp.sh"  # Deploy the app to the EC2 instance
